<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="author" content="Rowdy Klijnsmit">
	<meta name="version" content="1.0">

	<title>Login</title>

	<!-- CSS Files -->
	<link rel="stylesheet" href="/basic.css">

	<!-- JavaScript Files -->
	<script src="/jquery.js"></script>
	<script src="/bootstrap.js"></script>
	<script src="/custom.js"></script>

</head>
<body id="login">
	<div id="blur"></div>
		
	<form action="/login/check/" method="post" class="form-horizontal full-center col-md-4">
		
		<div class="form-group">
			<label for="username">Username:</label>
			<input type="text" name="username" id="username" class="form-control" placeholder="John Doe" autofocus>
		</div>

		<div class="form-group">
			<label for="password">Password:</label>
			<input type="password" name="password" id="password" class="form-control" placeholder="John Doe">
		</div>

		<div class="form-group">
			<input type="submit" value="Login" class="btn btn-default">
		</div>

	</form>

</body>
</html>